import { Button, VerticalBox, LineEdit} from "std-widgets.slint";

export component AppWindow inherits Window {
    // background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 30px;
        Row {
            Text {
                text: "Enter your Income";
                horizontal-alignment: center;
                font-size: 25px;
                font-weight: 900;
            }
        }
        Row {
            LineEdit {
                horizontal-alignment: center;
                font-size: 15px;
                padding: 5px;
                placeholder-text: "00.00";
                height: 35px;
            }
        }
        Row {
            Button { 
                text: "Calculate";
                primary: true;
                height: 35px;
            }
        }
    }
}
